import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { BillingRecord } from '../types';

export const generateInvoicePDF = (record: BillingRecord): void => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("ElectroStock Inventory", 14, 20);
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text("Electronics Inventory Management System", 14, 26);
  
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(37, 99, 235); // #2563eb
  doc.text("INVOICE", 196, 20, { align: "right" });
  
  doc.setFontSize(12);
  doc.setTextColor(50);
  doc.text(record.id, 196, 28, { align: "right" });
  
  doc.setDrawColor(200);
  doc.line(14, 32, 196, 32);
  
  // Details
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0);
  doc.text("Bill To:", 14, 42);
  doc.setFont("helvetica", "normal");
  doc.text(record.customerName, 14, 48);
  doc.text(record.customerEmail, 14, 54);
  
  doc.setFont("helvetica", "bold");
  doc.text("Invoice Date:", 120, 42);
  doc.text("Status:", 120, 48);
  doc.text("Invoice ID:", 120, 54);
  
  doc.setFont("helvetica", "normal");
  doc.text(new Date(record.date).toLocaleDateString(), 150, 42);
  
  let statusColor = [0, 0, 0];
  if (record.status === 'Paid') statusColor = [22, 163, 74];
  else if (record.status === 'Unpaid') statusColor = [245, 158, 11];
  else if (record.status === 'Cancelled') statusColor = [220, 38, 38];
  
  doc.setTextColor(statusColor[0], statusColor[1], statusColor[2]);
  doc.text(record.status, 150, 48);
  
  doc.setTextColor(0);
  doc.text(record.id, 150, 54);

  // Table
  const prodName = record.productName.length > 30 ? record.productName.substring(0, 30) + "..." : record.productName;
  
  autoTable(doc, {
    startY: 65,
    head: [['#', 'Product Name', 'Quantity', 'Unit Price', 'Total']],
    body: [
      ['1', prodName, record.quantity.toString(), `$${record.pricePerUnit.toFixed(2)}`, `$${record.total.toFixed(2)}`]
    ],
    headStyles: { fillColor: [37, 99, 235], textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: [245, 247, 250] },
    theme: 'grid'
  });
  
  const finalY = (doc as any).lastAutoTable.finalY || 65;
  
  // Summary
  doc.setFontSize(10);
  doc.text(`Subtotal:`, 150, finalY + 10);
  doc.text(`$${record.total.toFixed(2)}`, 196, finalY + 10, { align: "right" });
  
  doc.text(`Tax (0%):`, 150, finalY + 16);
  doc.text(`$0.00`, 196, finalY + 16, { align: "right" });
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text(`Total:`, 150, finalY + 24);
  doc.text(`$${record.total.toFixed(2)}`, 196, finalY + 24, { align: "right" });
  
  if (record.notes?.trim()) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("Notes:", 14, finalY + 15);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100);
    doc.text(record.notes, 14, finalY + 20, { maxWidth: 100 });
  }
  
  // Footer
  doc.setTextColor(150);
  doc.setFontSize(9);
  doc.text("Thank you for your business!", 105, 280, { align: "center", baseline: "bottom" });
  doc.text(`Generated by ElectroStock — ${new Date().toLocaleDateString()}`, 105, 285, { align: "center", baseline: "bottom" });
  
  doc.save(`Invoice-${record.id}.pdf`);
};

export const generateBillingReportPDF = (records: BillingRecord[]): void => {
  const doc = new jsPDF('landscape');
  
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("ElectroStock Inventory — Billing Report", 14, 20);
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text(`Generated on: ${new Date().toLocaleString()}`, 14, 26);
  doc.text(`Total Records: ${records.length}`, 14, 32);
  
  doc.setDrawColor(200);
  doc.line(14, 36, 283, 36);
  
  const body = records.map(r => {
    const pName = r.productName.length > 30 ? r.productName.substring(0, 30) + "..." : r.productName;
    return [
      r.id,
      r.customerName,
      r.customerEmail,
      pName,
      r.quantity.toString(),
      `$${r.pricePerUnit.toFixed(2)}`,
      `$${r.total.toFixed(2)}`,
      r.status,
      new Date(r.date).toLocaleDateString()
    ];
  });
  
  autoTable(doc, {
    startY: 42,
    head: [['Invoice ID', 'Customer', 'Email', 'Product', 'Qty', 'Unit Price', 'Total', 'Status', 'Date']],
    body: body,
    headStyles: { fillColor: [37, 99, 235], textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: [245, 247, 250] },
    theme: 'grid',
    didParseCell: function(data) {
      if (data.section === 'body' && data.column.index === 7) {
        const text = data.cell.raw as string;
        if (text === 'Paid') data.cell.styles.textColor = [22, 163, 74];
        else if (text === 'Unpaid') data.cell.styles.textColor = [245, 158, 11];
        else if (text === 'Cancelled') data.cell.styles.textColor = [220, 38, 38];
      }
    }
  });

  const pageCount = (doc as any).internal.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    // Footer bottom left
    doc.text("ElectroStock Inventory Management System", 14, 200);
    // Footer bottom right
    doc.text(`Page ${i} of ${pageCount}`, 283, 200, { align: 'right' });
  }

  doc.save(`ElectroStock-Billing-Report-${new Date().toISOString().split('T')[0]}.pdf`);
};
